### ISSUE TITLE
pdx225 - android.hardware.boot@1.2-impl-qti.recovery already defined by device/sony/pdx225/bootctrl

### ISSUE THREAD

**Issue by ekaats** [XperiaLabs/bug_tracker#1]
**Device:**
PDX225 - XQ-CC54

**Android Version:**
Lineage 21 - Android 14

**Description**:
Probably I am using the wrong repo's. I've been trying to fix this by removing occurrences from device/pdx225 but that didn't help. If its better to place these kind of questions on xdaforums I'll do so in the future.

> [ 46% 138/296] including out/soong/installs-lineage_pdx225.mk ...
> [ 46% 139/296] including out/soong/Android-lineage_pdx225.mk ...
> FAILED: 
> In file included from out/soong/installs-lineage_pdx225.mk:380689:
> In file included from out/soong/Android-lineage_pdx225.mk:300006:
> In file included from build/make/core/soong_cc_rust_prebuilt.mk:76:
> build/make/core/base_rules.mk:300: error: hardware/sony/bootctrl: MODULE.TARGET.SHARED_LIBRARIES.android.hardware.boot@1.2-impl-qti.recovery already defined by device/sony/pdx225/bootctrl.
> 10:17:11 ckati failed with: exit status 1

I'm building with the latest docker image of lineageos-microg. Weirdly enough running breakfast myself gives me an error that lunch cannot be presented.

Repo's I am using:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="XperiaLabs/kernel_sony_murami" path="device/sony/sm6375" remote="github" revision="Krispy-v2.0.2"/>
  <project name="XperiaLabs/device_sony_pdx225" path="device/sony/pdx225" remote="github" revision="Lineage"/>
  <project name="XperiaLabs/vendor_sony_extra" path="vendor/sony/extra" remote="github" revision="14_UDC"/>
  <project name="XperiaLabs/vendor_sony_pdx225" path="vendor/sony/pdx225" remote="github" revision="A14"/>
  <project name="XperiaLabs/hardware_sony" path="hardware/sony" remote="github" revision="Murami"/>
</manifest>
```

**Comment by saku-bruh** [comment]
Hi, we don't support AOSP pdx225 trees anymore and they are very outdated (that's probably why you're getting the error, they haven't been updated in months) since Spectre wants to try doing AOSPA for it but you could try doing the following in your ROM directory:
`rm -rf hardware/sony/bootctrl`
